name: Release

on:
  pull_request:
    types: closed
    branches: 
      - master

jobs:
  build:
    runs-on: macOS-latest
    
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
        with:
          ref: refs/heads/${{ github.head_ref }}

      - name: Get dependencies
        run: go get -v -t -d ./...
  
      - name: Build Application
        run: make zip 
            
      - name: Tag
        id: tag
        uses: K-Phoen/semver-release-action@master
        with:
          release_branch: master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: GoFast.zip
          asset_name: gofast
          tag: ${{ steps.tag.outputs.tag }}
          overwrite: true
        
      
