name: Release

on:
  pull_request:
    types: closed
    branches: 
      - master

jobs:
  build:
    runs-on: macOS-latest
    
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
        with:
          # This is a workaround for the `closed` action for PRs.
          ref: ${{github.event.pull_request.head.ref }}

      - name: Get dependencies
        run: go get -v -t -d ./...

      - name: Prepare certificate
        run: |
          echo $MAC_CERT | base64 --decode > cert.p12
        env:
          MAC_CERT: ${{ secrets.MAC_CERT }}
  
      - name: Setup Keychain
        run: |
          security create-keychain -p ${{ secrets.PASSWORD }} build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p ${{ secrets.PASSWORD }} build.keychain
          # I think this is insecure, but there's no real way I can do it otherwise.
          # TODO: Maybe wrap this in a separate action that doesn't use logging.
          security import cert.p12 -k build.keychain -t agg -f pkcs12 -P ${{ secrets.PASSWORD }}
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k ${{ secrets.PASSWORD }} build.keychain
  
      - name: Sign Application
        run: make sign 
        env:
          APPLE_ID: ${{ secrets.APPLE_CERT }}

      - name: Tag
        id: tag
        uses: K-Phoen/semver-release-action@master
        with:
          release_branch: master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: GoFast.zip
          asset_name: gofast
          tag: ${{ steps.tag.outputs.tag }}
          overwrite: true
        
      
